import { StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    backgroundColor: "#181828",
    fontFamily: "Panton",
    padding: 32,
    fontSize: 14,
    color: "#fff",
    border: "4px solid #00fff7",
    boxShadow: "0 0 24px 4px #00fff7, 0 0 64px 8px #ff00ea",
    position: "relative",
  },
  header: {
    backgroundColor: "rgba(0,0,0,0.25)",
    padding: 20,
    textAlign: "center",
    fontFamily: "PantonBold",
    borderRadius: 16,
    border: "2px solid #ff00ea",
    boxShadow: "0 0 12px 2px #ff00ea",
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    fontFamily: "PantonBold",
    color: "#00fff7",
    textShadow: "0 0 8px #00fff7, 0 0 16px #00fff7",
    letterSpacing: 2,
  },
  subtitle: {
    fontSize: 22,
    marginTop: 10,
    fontFamily: "Panton",
    color: "#ff00ea",
    textShadow: "0 0 6px #ff00ea, 0 0 12px #ff00ea",
  },
  body: {
    marginTop: 24,
    textAlign: "center",
    fontFamily: "Panton",
    color: "#fff",
  },
  paragraph: {
    marginBottom: 10,
    fontSize: 16,
    fontFamily: "Panton",
    color: "#fff",
    textShadow: "0 0 4px #00fff7",
  },
  bold: {
    fontWeight: "bold",
    fontFamily: "PantonBold",
    color: "#ff00ea",
    textShadow: "0 0 6px #ff00ea",
  },
  activities: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    fontFamily: "Panton",
  },
  activity: {
    margin: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
    border: "1.5px dashed #00fff7",
    borderRadius: 10,
    fontSize: 12,
    fontFamily: "Panton",
    color: "#00fff7",
    textShadow: "0 0 4px #00fff7",
  },
  meetup: {
    marginTop: 20,
    color: "#ff00ea",
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: "PantonBold",
    textShadow: "0 0 6px #ff00ea",
  },
  contact: {
    marginTop: 14,
    fontSize: 12,
    fontFamily: "Panton",
    color: "#fff",
    textShadow: "0 0 3px #00fff7",
  },
  footer: {
    marginTop: 24,
    paddingTop: 10,
    fontSize: 10,
    textAlign: "center",
    fontFamily: "Calibri",
    color: "#00fff7",
    alignItems: "center",
    textShadow: "0 0 4px #00fff7",
  },
  qrBlock: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 32,
    paddingHorizontal: 24,
    gap: 16,
  },
  qrItem: {
    alignItems: "center",
    width: 120,
  },
  qrLabel: {
    marginTop: 8,
    fontSize: 10,
    color: "#fff",
    textAlign: "center",
    textShadow: "0 0 3px #00fff7",
  },
  qrImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#222",
    borderStyle: "solid",
    backgroundColor: "#fff",
  },
  invitationTitleBox: {
    backgroundColor: "#181828",
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginBottom: 8,
    boxShadow: "0 0 12px 2px #181828",
    border: "2px solid #00fff7",
    alignItems: "center",
    zIndex: 100,
  },
});

export default styles;
